### ISSUE TITLE
Missing Model File mineclip_image_encoder_vit-B_196tokens.pth

### ISSUE THREAD

**Issue by CjangCjengh** [IranQin/MP5#4]
Hello,

I hope this message finds you well. I encountered an issue while running 
```sh
python mllm_api_mc_v1.5.py
```
The script seems to require the file `mineclip_image_encoder_vit-B_196tokens.pth`, but this file is missing from the repository. Unfortunately, I couldn't find any download link or information on how to obtain this particular model.

Could you please provide guidance on how to access or obtain `mineclip_image_encoder_vit-B_196tokens.pth`? It would greatly help me in using your code and experimenting with the model.

Thank you for your assistance.

**Comment by IranQin** [comment]
You can download the checkpoint in MineCLIP repo: https://github.com/MineDojo/MineCLIP, we also download it from this repo.

**Comment by Zhoues** [comment]
Sorry, we forgot to provide the corresponding download link.

You can download it from this URL `https://drive.google.com/file/d/1EGZLIefb8OsJ3mFCq9-AcSaG2GZRuech/view?usp=drive_link`
Or use the command to download `gdown https://drive.google.com/uc?id=1EGZLIefb8OsJ3mFCq9-AcSaG2GZRuech`

After downloading it, you can put it into the `LAMM/model_zoo/mineclip_ckpt` folder.
